/****************************************************************************
**
** TQt GUI Toolkit
**
** This header file efficiently includes all TQt GUI Toolkit functionality.
**
** Generated : Mon Oct 13 13:07:29 CEST 2003

**
** Copyright (C) 1995-2008 Trolltech ASA.  All rights reserved.
**
** This file is part of the TQt GUI Toolkit.
**
*****************************************************************************/

#ifndef QT_H
#define QT_H
#include <tqglobal.h>
#include <tqfeatures.h>
#include <tqshared.h>
#include <tqptrcollection.h>
#include <tqglist.h>
#include <tqobjectdefs.h>
#include <tqnamespace.h>
#include <tqgarray.h>
#include <tqmemarray.h>
#include <tqcstring.h>
#include <tqstring.h>
#include <tqptrlist.h>
#include <tqiodevice.h>
#include <tqkeysequence.h>
#include <tqwindowdefs.h>
#include <tqgdict.h>
#include <tqfont.h>
#include <tqdatastream.h>
#include <tqpair.h>
#include <tqpoint.h>
#include <stdio.h>
#include <tqtextstream.h>
#include <tqfontinfo.h>
#include <tqsizepolicy.h>
#include <tqtl.h>
#include <tqsize.h>
#include <tqrect.h>
#include <tqbitarray.h>
#include <tqregion.h>
#include <tqsql.h>
#include <tqstrlist.h>
#include <tqvaluelist.h>
#include <tqmap.h>
#include <tqdatetime.h>
#include <tqmime.h>
#include <tqasciidict.h>
#include <tqpaintdevice.h>
#include <tqfontmetrics.h>
#include <tqdict.h>
#include <tqevent.h>
#include <tqhostaddress.h>
#include <tqstringlist.h>
#include <tqcolor.h>
#include <tqdom.h>
#include <tqobject.h>
#include <tqdrawutil.h>
#include <tqbrush.h>
#include <tqpalette.h>
#include <tqwidget.h>
#include <tqjpunicode.h>
#include <tqtextcodec.h>
#include <tqpixmap.h>
#include <tqtabbar.h>
#include <tqiconset.h>
#include <tqbutton.h>
#include <tqtoolbutton.h>
#include <tqstyle.h>
#include <tqframe.h>
#include <tqfile.h>
#include <tqfileinfo.h>
#include <tqurlinfo.h>
#include <tqwidgetlist.h>
#include <tqcombobox.h>
#include <tqgroupbox.h>
#include <tqdialog.h>
#include <tqdataview.h>
#include <tqdockwindow.h>
#include <tqcommonstyle.h>
#include <tqnetworkprotocol.h>
#include <tqeuckrcodec.h>
#include <tqgb18030codec.h>
#include <tqgcache.h>
#include <tqgif.h>
#include <tqglcolormap.h>
#include <tqcache.h>
#include <tqdropsite.h>
#include <tqgplugin.h>
#include <tqgrid.h>
#include <tqrangecontrol.h>
#include <tqbuttongroup.h>
#include <tqdatetimeedit.h>
#include <tqgvector.h>
#include <tqhbox.h>
#include <tqhbuttongroup.h>
#include <tqhgroupbox.h>
#include <tqsocketnotifier.h>
#include <tqeventloop.h>
#include <tqhttp.h>
#include <tqaction.h>
#include <tqbuffer.h>
#include <tqimage.h>
#include <tqimageformatplugin.h>
#include <tqlineedit.h>
#include <tqintcache.h>
#include <tqintdict.h>
#include <tqmotifstyle.h>
#include <tqpicture.h>
#include <tqjiscodec.h>
#include <tqeucjpcodec.h>
#include <tqkeycode.h>
#include <tqaccel.h>
#include <tqlabel.h>
#include <tqlayout.h>
#include <tqlcdnumber.h>
#include <tqlibrary.h>
#include <tqinputdialog.h>
#include <tqscrollbar.h>
#include <tqscrollview.h>
#include <tqdir.h>
#include <tqwindowsstyle.h>
#include <tqconnection.h>
#include <tqbitmap.h>
#include <tqvariant.h>
#include <tqsignal.h>
#include <tqmessagebox.h>
#include <tqmetaobject.h>
#include <tqheader.h>
#include <tqmotifplusstyle.h>
#include <tqcdestyle.h>
#include <tqmovie.h>
#include <tqptrvector.h>
#include <tqmutex.h>
#include <tqnetwork.h>
#include <tqftp.h>
#include <tqguardedptr.h>
#include <tqobjectcleanuphandler.h>
#include <tqsqlfield.h>
#include <tqobjectdict.h>
#include <tqobjectlist.h>
#include <tqcolordialog.h>
#include <tqpaintdevicemetrics.h>
#include <tqpointarray.h>
#include <tqmenudata.h>
#include <tqlistview.h>
#include <tqpen.h>
#include <tqdragobject.h>
#include <tqiconview.h>
#include <tqpixmapcache.h>
#include <tqplatinumstyle.h>
#include <tqpngio.h>
#include <tqcursor.h>
#include <tqerrormessage.h>
#include <tqpolygonscanner.h>
#include <tqpopupmenu.h>
#include <tqprintdialog.h>
#include <tqprinter.h>
#include <tqprocess.h>
#include <tqprogressbar.h>
#include <tqasciicache.h>
#include <tqptrdict.h>
#include <tqcleanuphandler.h>
#include <tqptrqueue.h>
#include <tqptrstack.h>
#include <tqstylesheet.h>
#include <tqpushbutton.h>
#include <tqradiobutton.h>
#include <tqdial.h>
#include <tqdockarea.h>
#include <tqregexp.h>
#include <tqclipboard.h>
#include <tqhebrewcodec.h>
#include <tqlistbox.h>
#include <tqgridview.h>
#include <tqsemaphore.h>
#include <tqprogressdialog.h>
#include <tqsocketdevice.h>
#include <tqsessionmanager.h>
#include <tqsettings.h>
#include <tqsgistyle.h>
#include <tqfontdialog.h>
#include <tqtimer.h>
#include <tqsignalmapper.h>
#include <tqsignalslotimp.h>
#include <tqsimplerichtext.h>
#include <tqwmatrix.h>
#include <tqsizegrip.h>
#include <tqsjiscodec.h>
#include <tqslider.h>
#include <tqsocket.h>
#include <tqserversocket.h>
#include <tqdns.h>
#include <tqsound.h>
#include <tqspinbox.h>
#include <tqsplashscreen.h>
#include <tqsplitter.h>
#include <tqsqlerror.h>
#include <tqeditorfactory.h>
#include <tqsqlquery.h>
#include <tqsqlrecord.h>
#include <tqsqldriverplugin.h>
#include <tqsqlindex.h>
#include <tqsqlcursor.h>
#include <tqsqldriver.h>
#include <tqsqlform.h>
#include <tqtable.h>
#include <tqsqlpropertymap.h>
#include <tqsqldatabase.h>
#include <tqdatabrowser.h>
#include <tqsqlresult.h>
#include <tqsqlselectcursor.h>
#include <tqstatusbar.h>
#include <tqmenubar.h>
#include <tqcanvas.h>
#include <tqtranslator.h>
#include <tqstrvec.h>
#include <tqinterlacestyle.h>
#include <tqstylefactory.h>
#include <tqstyleplugin.h>
#include <tqtextedit.h>
#include <tqsyntaxhighlighter.h>
#include <tqtabdialog.h>
#include <tqsqleditorfactory.h>
#include <tqtabwidget.h>
#include <tqtextbrowser.h>
#include <tqbig5codec.h>
#include <tqtextcodecfactory.h>
#include <tqtextcodecplugin.h>
#include <tqmultilineedit.h>
#include <tqtoolbar.h>
#include <tqtextview.h>
#include <tqwaitcondition.h>
#include <tqasyncio.h>
#include <tqfontdatabase.h>
#include <tqmainwindow.h>
#include <tqtoolbox.h>
#include <tqtooltip.h>
#include <tqdesktopwidget.h>
#include <tqtsciicodec.h>
#include <tqurl.h>
#include <tqurloperator.h>
#include <tqfiledialog.h>
#include <tqutfcodec.h>
#include <tquuid.h>
#include <tqvalidator.h>
#include <tqasyncimageio.h>
#include <tqvaluestack.h>
#include <tqvaluevector.h>
#include <tqdatatable.h>
#include <tqvbox.h>
#include <tqvbuttongroup.h>
#include <tqvgroupbox.h>
#include <tqthread.h>
#include <tqwhatsthis.h>
#include <tqapplication.h>
#include <tqwidgetintdict.h>
#include <tqfocusdata.h>
#include <tqwidgetplugin.h>
#include <tqwidgetstack.h>
#include <tqcheckbox.h>
#include <tqcompactstyle.h>
#include <tqwizard.h>
#include <tqpainter.h>
#include <tqworkspace.h>
#include <tqlocalfs.h>
#include <tqxml.h>

#if defined( QT_MOC_CPP ) || defined( QT_H_CPP ) || defined( Q_OS_MACX )
#include <private/tqcom_p.h>
#include <private/tqucom_p.h>
#include <private/tqimageformatinterface_p.h>
#include <private/tqisciicodec_p.h>
#include <private/tqlayoutengine_p.h>
#include <private/tqcomlibrary_p.h>
#include <private/tqeffects_p.h>
#include <private/tqgpluginmanager_p.h>
#include <private/tqinternal_p.h>
#include <private/tqsqldriverinterface_p.h>
#include <private/tqsqlmanager_p.h>
#include <private/qlock_p.h>
#include <private/tqcomponentfactory_p.h>
#include <private/tqstyleinterface_p.h>
#include <private/tqrichtext_p.h>
#include <private/tqsvgdevice_p.h>
#include <private/tqfontcodecs_p.h>
#include <private/tqtextcodecinterface_p.h>
#include <private/tqpsprinter_p.h>
#include <private/tqtitlebar_p.h>
#include <private/tqucomextra_p.h>
#include <private/tqpluginmanager_p.h>
#include <private/tqdir_p.h>
#include <private/tqsettings_p.h>
#include <private/tqsqlextension_p.h>
#include <private/tqdialogbuttons_p.h>
#include <private/tqwidgetinterface_p.h>
#include <private/tqwidgetresizehandler_p.h>
#include <private/tqlibrary_p.h>
#endif // Private headers


#ifdef TQ_WS_X11
#include <private/tqttdeintegration_x11_p.h>
#endif

#ifdef TQ_WS_MAC
#include <qaquastyle.h>
#include <tqmacstyle_mac.h>
#endif // TQ_WS_MAC

#ifdef TQ_WS_WIN
#include <tqwindowsxpstyle.h>
#endif

#ifdef TQ_WS_WCE
#include <qpocketpcstyle_wce.h>
#endif // TQ_WS_WCE

#endif // QT_H
