#define TQ_EXPORT_TEMPLATES

#include <tqcanvas.h>
#include <tqaccessible.h>
#include <tqconnection.h>
#include <tqguardedptr.h>
#include <tqobject.h>
#include <tqpoint.h>
#include <tqrect.h>
#include <tqsignalslotimp.h>
#include <tqwidget.h>
#include <tqhttp.h>
#include <private/tqsqlextension_p.h>
#include <tqsqlindex.h>
#include <tqtable.h>
#include <tqasciidict.h>
#include <tqcstring.h>
#include <tqdict.h>
#include <tqintdict.h>
#include <tqlibrary.h>
#include <tqmap.h>
#include <tqmemarray.h>
#include <tqptrlist.h>
#include <tqptrvector.h>
#include <tqstring.h>
#include <tqvaluelist.h>
#include <tqvaluevector.h>
#include <tqdockarea.h>
#include <tqdockwindow.h>
